---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 443 ssl http2;
      server_name localhost;

      ssl_certificate /etc/nginx/ssl/server.crt;
      ssl_certificate_key /etc/nginx/ssl/server.key;

      ssl_session_timeout 5m;

      ssl_ciphers HIGH:!aNULL:!MD5;
      ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
      ssl_prefer_server_ciphers on;
      
      index index.html;
      root /usr/share/nginx/html;
      client_max_body_size 500m;
      client_header_buffer_size 32k;

      location ~ /$ {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }

      location ~ /*\..*$ {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
      
      location ~ /api/ {
        proxy_pass http://oms-gateway:8080;
        proxy_buffer_size 32k;
        proxy_buffers 8 32k;
        proxy_busy_buffers_size 36k;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-web
  labels:
    app: oms-web
spec:
  replicas: 1
  template:
    metadata:
      name: oms-web
      labels:
        app: oms-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: oms-web
          image: registry.cn-chengdu.aliyuncs.com/cestech/oms-web:IMAGE_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      restartPolicy: Always
  selector:
    matchLabels:
      app: oms-web
---
apiVersion: v1
kind: Service
metadata:
  name: oms-web
  labels:
    app: oms-web
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30000
  selector:
    app: oms-web
